### ISSUE TITLE
size of Initial condition panel

### ISSUE THREAD

**Issue by chaouiya** [epilog-tool/epilog#4]
Would be good if this panel was resizable? Here it is not possible to check/uncheck the components (see screen shot attached)

![screen shot 2018-06-09 at 19 07 04](https://user-images.githubusercontent.com/40125033/41194742-6e9a4444-6c18-11e8-8cbb-629610b881dd.png)

**Comment by PedroBLV** [comment]
The components list is a Horizontal Jscroll bar, and there is a slider on the bottom of the panel. 

For an easier use, we are adding tooltip boxes with the components name, and place the checkbox before the components name.
